### ISSUE TITLE
Static ler build edilmiyor

### ISSUE THREAD

**Issue by oyilmaztekin** [elyface/elyface-SSR#77]
stiller [chunk js](https://dev-haberiyakala.netlify.com/_next/static/chunks/styles.fb2e296de4c69bfac477.js) içerisinde mapleniyor `slide__title:"Lyp9v9Y9`

yine [chunk css](https://dev-haberiyakala.netlify.com/_next/static/css/styles.d1e584a5.chunk.css) içerisinde stiller işleniyor.

```css
.Lyp9v9Y9 {
  background-color: #ffa200;
  left: 0px;
  padding: 15px;
  text-align: left;
  display: block;
  color: #282841; }
```
class isimleri derlenmiş HTML içinde maplenmemiş. `Lyp9v9Y9` değiş`slide__title` olarak duruyor. view source olarak girilip class arandığında maplenmiş olarak değil sass içinde verilen isimlendirmesiyle duruyor.
